[workspace]
members = [
    "rustyguard-core",
    "rustyguard-crypto",
    "rustyguard-tun",
    "rustyguard-types",
    "rustyguard-utils",
    "rustyguard-aws-lc",
    "wg-proxy",
]
resolver = "2"
